version: '3.8'

services:
  app:
    container_name: teamview-app
    build: .
    command: npm run start
    depends_on: [db]
    ports:
      - "3002:3000"
    links: [db]
    restart: unless-stopped

  db:
    container_name: teamview-db
    image: postgres:latest
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    restart: unless-stopped
